name: flutter_sheet_localization
description: Annotations for the flutter_sheet_localization_generator package.
version: 2.0.1
homepage: https://github.com/aloisdeniel/flutter_sheet_localization

environment:
  sdk: '>=2.7.0 <3.0.0'
